export enum IGEN_CV_STATUS {
  STARTING = 'STARTING',
  UPLOADING = 'UPLOADING',
  TRANSCRIPTING = 'TRANSCRIPTING',
  GENERATING = 'GENERATING',
  COMPLETING = 'COMPLETING',
}

export type IGenerateCV = keyof typeof IGEN_CV_STATUS;
