import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(__dirname, '../../.env') });

const {
  ORIGIN,
  PORT,
  NODE_ENV,
  CLIENT_ORIGIN,
  SESSION_SECRET,
  REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT,
  API_KEY,
  FREE_ACCESS_EMAIL,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  OPENAI_API_KEY,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_SECRET_KEY,
  AAI_API_KEY,
  SERVERLESS_FN,
  GEN_POSTS_DEV_TEST_API_KEY,
  SERVERLESS_API_KEY,
  QSTASH_API_KEY,
} = process.env;

export {
  AAI_API_KEY,
  ACCESS_TOKEN_SECRET,
  API_KEY,
  CLIENT_ORIGIN,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_SECRET_KEY,
  FREE_ACCESS_EMAIL,
  GEN_POSTS_DEV_TEST_API_KEY,
  NODE_ENV,
  OPENAI_API_KEY,
  ORIGIN,
  PORT,
  QSTASH_API_KEY,
  REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT,
  REFRESH_TOKEN_SECRET,
  SERVERLESS_API_KEY,
  SERVERLESS_FN,
  SESSION_SECRET,
};
