openapi: 3.0.0
components:
  schemas:
    RegisterUser:
      type: object
      required:
        - userName
        - pwd
        - email
      properties:
        userName:
          type: string
          description: The name of the User.
        pwd:
          type: string
          description: The User Password.
        email:
          type: string
          description: The email of the User.
    LoginUser:
      type: object
      required:
        - pwd
        - identity
      properties:
        identity:
          type: string
          description: The username or email of the user.
        pwd:
          type: string
          description: The User Password.
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
info:
  title: Welcome to Upshot API Docs
  description: Explore the various routes available at Upshot.
  version: 0.0.0
servers:
  - url: http://localhost:8080
    description: Local Server for Upshot API
apis: ['./src/routes/*.route.ts']
security:
  - apiKey: []
  - bearerAuth: []
paths:
  /api/v1/auth/register:
    post:
      summary: Registers A New User.
      description: Registers a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '201':    
          description: Successful User Registration
        '403':
          description: API KEY not found. Hence Forbidden!
  /api/v1/auth/login:
    post:
      summary: Logs in An Existing User using email/username & password.
      description: Logs in An Existing User using email/username & password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '201':    
          description: Successful User Login
        '403':
          description: API KEY not found. Hence Forbidden!
  /api/v1/auth/logout:
    post:
      summary: Logs out An Existing User .
      description: Logs Out An Existing User .
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutUser'
      responses:
        '204':    
          description: Successful User Login
        '403':
          description: API KEY not found. Hence Forbidden!